# Config file for automatic testing at travis-ci.org

language: python

sudo: required

dist: trusty

python:
  - 3.5
  - 3.4
  - 2.7

env:
  matrix:
  - DJANGO='django18' CMS='cms31'
  - DJANGO='django18' CMS='cms32'
  - DJANGO='django18' CMS='cms33'
  - DJANGO='django18' CMS='cms34'
  - DJANGO='django19' CMS='cms32'
  - DJANGO='django19' CMS='cms33'
  - DJANGO='django19' CMS='cms34'
  - TOXENV='pep8'
  - TOXENV='isort'

before_install:
  - >
    if [[ ${DJANGO}z != 'z' ]];
    then sudo apt-get -qq update;
    sudo apt-get install -y texlive;
    sudo apt-get install -y dvipng; fi

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
  - pip install -U tox>=1.8 coveralls
  - "if [[ $TRAVIS_PYTHON_VERSION == '2.7' ]]; then export PYVER=py27; fi"
  - "if [[ $TRAVIS_PYTHON_VERSION == '3.3' ]]; then export PYVER=py33; fi"
  - "if [[ $TRAVIS_PYTHON_VERSION == '3.4' ]]; then export PYVER=py34; fi"
  - "if [[ $TRAVIS_PYTHON_VERSION == '3.5' ]]; then export PYVER=py35; fi"
  - "if [[ ${DJANGO}z != 'z' ]]; then export TOXENV=$PYVER-$DJANGO-$CMS; fi"


# command to run tests, e.g. python setup.py test
script: COMMAND='coverage run' tox -e$TOXENV

after_success: coveralls

matrix:
  exclude:
  - python: 3.4
    env: TOXENV='pep8'
  - python: 3.4
    env: TOXENV='isort'
  - python: 3.5
    env: TOXENV='pep8'
  - python: 3.5
    env: TOXENV='isort'

cache:
   directories:
     - $HOME/.cache/pip
